In [2]:
import numpy as np
import math
import time

In [20]:
points = np.genfromtxt("income.csv", delimiter=",")
points = np.c_[np.ones(len(points)),points]

In [21]:
points

array([[  1.        ,  10.        ,  26.65883878],
       [  1.        ,  10.40133779,  27.30643535],
       [  1.        ,  10.84280936,  22.13241017],
       [  1.        ,  11.24414716,  21.1698405 ],
       [  1.        ,  11.64548495,  15.19263352],
       [  1.        ,  12.08695652,  26.39895104],
       [  1.        ,  12.48829431,  17.43530658],
       [  1.        ,  12.88963211,  25.50788523],
       [  1.        ,  13.2909699 ,  36.88459469],
       [  1.        ,  13.73244147,  39.66610875],
       [  1.        ,  14.13377926,  34.39628056],
       [  1.        ,  14.53511706,  41.49799354],
       [  1.        ,  14.97658863,  44.98157487],
       [  1.        ,  15.37792642,  47.03959526],
       [  1.        ,  15.77926421,  48.25257829],
       [  1.        ,  16.22073579,  57.03425134],
       [  1.        ,  16.62207358,  51.49091921],
       [  1.        ,  17.02341137,  61.33662055],
       [  1.        ,  17.46488294,  57.58198818],
       [  1.        ,  17.86622

In [33]:
X = points[:,[0,1]] #Pega todas as linhas das colunas 0 e 1 (convertendo essas duas em um array) 
X

array([[  1.        ,  10.        ],
       [  1.        ,  10.40133779],
       [  1.        ,  10.84280936],
       [  1.        ,  11.24414716],
       [  1.        ,  11.64548495],
       [  1.        ,  12.08695652],
       [  1.        ,  12.48829431],
       [  1.        ,  12.88963211],
       [  1.        ,  13.2909699 ],
       [  1.        ,  13.73244147],
       [  1.        ,  14.13377926],
       [  1.        ,  14.53511706],
       [  1.        ,  14.97658863],
       [  1.        ,  15.37792642],
       [  1.        ,  15.77926421],
       [  1.        ,  16.22073579],
       [  1.        ,  16.62207358],
       [  1.        ,  17.02341137],
       [  1.        ,  17.46488294],
       [  1.        ,  17.86622074],
       [  1.        ,  18.26755853],
       [  1.        ,  18.7090301 ],
       [  1.        ,  19.11036789],
       [  1.        ,  19.51170569],
       [  1.        ,  19.91304348],
       [  1.        ,  20.35451505],
       [  1.        ,  20.75585284],
 

In [35]:
X.shape #Número de linhas e colunas

(30, 2)

In [46]:
Y = points[:,2][:,np.newaxis] #Pega todas as linhas da coluna 2
#Y = points[:,[2]] #Retorna o mesmo do anterior

#Y = points[:,2] #Dessa forma não retorna o número de colunas. Estranho.
Y

array([[ 26.65883878],
       [ 27.30643535],
       [ 22.13241017],
       [ 21.1698405 ],
       [ 15.19263352],
       [ 26.39895104],
       [ 17.43530658],
       [ 25.50788523],
       [ 36.88459469],
       [ 39.66610875],
       [ 34.39628056],
       [ 41.49799354],
       [ 44.98157487],
       [ 47.03959526],
       [ 48.25257829],
       [ 57.03425134],
       [ 51.49091921],
       [ 61.33662055],
       [ 57.58198818],
       [ 68.55371402],
       [ 64.3109253 ],
       [ 68.95900864],
       [ 74.61463928],
       [ 71.8671953 ],
       [ 76.09813538],
       [ 75.77521803],
       [ 72.48605532],
       [ 77.35502057],
       [ 72.11879045],
       [ 80.2605705 ]])

In [50]:
Y.shape

(30, 1)

In [49]:
Y[:,0]

array([ 26.65883878,  27.30643535,  22.13241017,  21.1698405 ,
        15.19263352,  26.39895104,  17.43530658,  25.50788523,
        36.88459469,  39.66610875,  34.39628056,  41.49799354,
        44.98157487,  47.03959526,  48.25257829,  57.03425134,
        51.49091921,  61.33662055,  57.58198818,  68.55371402,
        64.3109253 ,  68.95900864,  74.61463928,  71.8671953 ,
        76.09813538,  75.77521803,  72.48605532,  77.35502057,
        72.11879045,  80.2605705 ])

In [51]:
grad = np.array([np.inf,np.inf])

In [54]:
grad

array([ inf,  inf])